### ISSUE TITLE
Lỗi "Navigator operation requested with a context that does not include a Navigator." khi sử dụng Navigator

### ISSUE THREAD

**Issue by zeroclubvn** [zeroclubvn/FlutterError2Hero#1]
======== Exception caught by gesture ==============
The following assertion was thrown while handling a gesture:
Navigator operation requested with a context that does not include a Navigator.

The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
When the exception was thrown, this was the stack: 
#0      Navigator.of.<anonymous closure> (package:flutter/src/widgets/navigator.dart:2553:9)
#1      Navigator.of (package:flutter/src/widgets/navigator.dart:2560:6)
#2      Navigator.push (package:flutter/src/widgets/navigator.dart:2016:22)
#3      MyMultiScreen.build.<anonymous closure> (package:multiscreen/main.dart:23:25)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)

**Comment by zeroclubvn** [comment]
![image](https://user-images.githubusercontent.com/96557038/154615360-3cd0a199-e674-4936-9588-eb1d18f2d575.png)
Cách đơn giản nhất mà mình dùng đó là Extract cái widget ở main.dart (như trong hình) là đã có thể sửa dc lỗi ngay.
